apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          ports:
            - containerPort: 31337
          envFrom:
            - secretRef:
                name: forcad-postgres-secret
            - secretRef:
                name: forcad-rabbitmq-secret
            - secretRef:
                name: forcad-redis-secret
          env:
            - name: PORT
              value: "31337"
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            tcpSocket:
              port: 31337
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            tcpSocket:
              port: 31337
