version: '2.4'

services:
  celery:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    environment:
      - TEST
      - CELERY_CONTAINER_TYPE=worker
    volumes:
      - ./checkers/:/checkers/
    env_file:
      - ./docker_config/postgres/environment.env
      - ./docker_config/redis/environment.env
      - ./docker_config/rabbitmq/environment.env
    restart: on-failure

  celerybeat:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    environment:
      - TEST
      - CELERY_CONTAINER_TYPE=beat
    env_file:
      - ./docker_config/postgres/environment.env
      - ./docker_config/redis/environment.env
      - ./docker_config/rabbitmq/environment.env
    restart: on-failure

  flower:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile
    environment:
      - TEST
      - CELERY_CONTAINER_TYPE=flower
    env_file:
      - ./docker_config/postgres/environment.env
      - ./docker_config/redis/environment.env
      - ./docker_config/celery/flower.env
      - ./docker_config/rabbitmq/environment.env
    restart: on-failure


  initializer:
    build:
      context: .
      dockerfile: docker_config/initializer/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
      - ./docker_config/redis/environment.env
      - ./docker_config/rabbitmq/environment.env
    environment:
      - TEST
    restart: on-failure

  webapi:
    build:
      context: .
      dockerfile: docker_config/webapi/Dockerfile
    env_file:
      - ./docker_config/webapi/environment.env
      - ./docker_config/postgres/environment.env
      - ./docker_config/redis/environment.env
      - ./docker_config/rabbitmq/environment.env
    environment:
      - TEST
    restart: on-failure

  gevent_flag_receiver:
    build:
      context: .
      dockerfile: docker_config/gevent_flag_receiver/Dockerfile
    env_file:
      - ./docker_config/postgres/environment.env
      - ./docker_config/redis/environment.env
      - ./docker_config/rabbitmq/environment.env
    ports:
      - 31337:31337
    environment:
      - TEST
    tty: true
    restart: on-failure

  nginx:
    build:
      context: .
      dockerfile: docker_config/nginx/Dockerfile
    ports:
      - 8080:80
      - 80:80
    restart: on-failure

  redis:
    image: redis:5.0.8-alpine
    command: ["sh", "-c", "redis-server --requirepass $$REDIS_PASSWORD"]
    restart: on-failure
    sysctls:
      net.core.somaxconn: 1024
    env_file:
      - ./docker_config/redis/environment.env
    ports:
      - "6379:6379"

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.8.3-management-alpine
    restart: on-failure
    env_file:
      - ./docker_config/rabbitmq/environment.env
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:12.2
    volumes:
      - ./docker_volumes/postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./docker_config/postgres/environment.env
    restart: on-failure
    ports:
      - "5432:5432"
      - "6432:5432"
