version: '2.4'

services:
  celery:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile.fast
    restart: "no"

  celerybeat:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile.fast
    restart: "no"

  flower:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile.fast
    restart: "no"

  initializer:
    build:
      context: .
      dockerfile: docker_config/initializer/Dockerfile.fast
    restart: "no"

  webapi:
    build:
      context: .
      dockerfile: docker_config/webapi/Dockerfile.fast
    restart: "no"

  gevent_flag_receiver:
    build:
      context: .
      dockerfile: docker_config/gevent_flag_receiver/Dockerfile.fast
    restart: "no"

  nginx:
    restart: "no"

  redis:
    restart: "no"

  postgres:
    restart: "no"

  rabbitmq:
    restart: "no"

  test_service:
    build:
      context: .
      dockerfile: docker_config/test_service/Dockerfile
    ports:
      - 10000:10000
    restart: "no"
