version: '2.4'

services:
  celery:
    build:
      context: .
      dockerfile: &fast-celery-dockerfile ./docker_config/celery/Dockerfile.fast
    restart: "no"

  celerybeat:
    build:
      context: .
      dockerfile: *fast-celery-dockerfile
    restart: "no"

  flower:
    build:
      context: .
      dockerfile: *fast-celery-dockerfile
    restart: "no"

  initializer:
    build:
      context: .
      dockerfile: ./docker_config/initializer/Dockerfile.fast
    restart: "no"

  client_api:
    build:
      context: .
      dockerfile: &fast-services-dockerfile ./docker_config/services/Dockerfile.fast
    restart: "no"

  admin_api:
    build:
      context: .
      dockerfile: *fast-services-dockerfile
    restart: "no"

  events:
    build:
      context: .
      dockerfile: *fast-services-dockerfile
    restart: "no"

  monitoring:
    build:
      context: .
      dockerfile: *fast-services-dockerfile
    restart: "no"

  tcp_receiver:
    build:
      context: .
      dockerfile: *fast-services-dockerfile
    restart: "no"

  nginx:
    restart: "no"

  redis:
    restart: "no"

  postgres:
    restart: "no"

  rabbitmq:
    restart: "no"

  test_service:
    build:
      context: .
      dockerfile: ./docker_config/test_service/Dockerfile
    ports:
      - 10000:10000
    restart: "no"
