version: '2.4'

volumes:
  front_build:

services:
  celery:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile.fast

  celerybeat:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile.fast

  flower:
    build:
      context: .
      dockerfile: docker_config/celery/Dockerfile.fast

  initializer:
    build:
      context: .
      dockerfile: docker_config/initializer/Dockerfile.fast

  webapi:
    build:
      context: .
      dockerfile: docker_config/webapi/Dockerfile.fast

  gevent_flag_submitter:
    build:
      context: .
      dockerfile: docker_config/gevent_flag_submitter/Dockerfile.fast
