version: '2.4'

volumes:
  front_build:

services:
  celery:
    build:
      context: .
      dockerfile: &fast-celery-dockerfile ./docker_config/celery/Dockerfile.fast

  celerybeat:
    build:
      context: .
      dockerfile: *fast-celery-dockerfile

  flower:
    build:
      context: .
      dockerfile: *fast-celery-dockerfile

  initializer:
    build:
      context: .
      dockerfile: ./docker_config/initializer/Dockerfile.fast

  admin_api:
    build:
      context: .
      dockerfile: &fast-services-dockerfile ./docker_config/services/Dockerfile.fast

  events:
    build:
      context: .
      dockerfile: *fast-services-dockerfile

  monitoring:
    build:
      context: .
      dockerfile: *fast-services-dockerfile

  tcp_receiver:
    build:
      context: .
      dockerfile: *fast-services-dockerfile
