apiVersion: batch/v1
kind: Job
metadata:
  name: initializer
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: initializer
          image: forcad-initializer
          envFrom:
            - secretRef:
                name: forcad-postgres-secret
            - secretRef:
                name: forcad-rabbitmq-secret
            - secretRef:
                name: forcad-redis-secret
      restartPolicy: OnFailure
