apiVersion: batch/v1
kind: Job
metadata:
  name: initializer
spec:
  template:
    spec:
      containers:
        - name: initializer
          image: forcad-initializer
          envFrom:
            - secretRef:
                name: forcad-db-secrets
      restartPolicy: OnFailure
