apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: forcad-admin-api
      context: .
      docker:
        dockerfile: ./docker_config/services/Dockerfile
    - image: forcad-client-api
      context: .
      docker:
        dockerfile: ./docker_config/services/Dockerfile
    - image: forcad-events
      context: .
      docker:
        dockerfile: ./docker_config/services/Dockerfile
    - image: forcad-http-receiver
      context: .
      docker:
        dockerfile: ./docker_config/services/Dockerfile
    - image: forcad-tcp-receiver
      context: .
      docker:
        dockerfile: ./docker_config/services/Dockerfile
    - image: forcad-monitoring
      context: .
      docker:
        dockerfile: ./docker_config/services/Dockerfile
    - image: forcad-initializer
      context: .
      docker:
        dockerfile: ./docker_config/initializer/Dockerfile
    - image: forcad-nginx
      context: .
      docker:
        dockerfile: ./docker_config/nginx/Dockerfile
  tagPolicy:
    gitCommit: { }
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths: [ "deploy" ]
