name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Setup release
        run: |
          echo ${{ steps.get_version.outputs.VERSION }} > .version
          ./scripts/prepare_release.sh

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: ForcAD_${{ steps.get_version.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
