name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup release
        run: |
          echo ${ GITHUB_REF#refs/*/ } > .version
          ./scripts/prepare_release.sh

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: ForcAD_${ GITHUB_REF#refs/*/ }.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
